In [1]:
import yfinance
import pandas as pd
import json
import datetime as dt

In [2]:
ticker_name = yfinance.Ticker('CBA.AX')
ticker_name.info

{'address1': 'Commonwealth Bank Place South',
 'address2': 'Level 1 11 Harbour Street',
 'city': 'Sydney',
 'state': 'NSW',
 'zip': '2000',
 'country': 'Australia',
 'phone': '61 2 9378 2000',
 'fax': '61 2 9118 7192',
 'website': 'https://www.commbank.com.au',
 'industry': 'Banks - Diversified',
 'industryKey': 'banks-diversified',
 'industryDisp': 'Banks - Diversified',
 'sector': 'Financial Services',
 'sectorKey': 'financial-services',
 'sectorDisp': 'Financial Services',
 'longBusinessSummary': 'Commonwealth Bank of Australia provides financial services in Australia, New Zealand, and internationally. It operates through Retail Banking Services, Business Banking, Institutional Banking and Markets, and New Zealand segments. The company offers transaction, savings, and foreign currency accounts; term deposits; personal and business loans; overdrafts; equipment finance; credit cards; international payment and trade; and private banking services, as well as home and car loans. It also provides retail, premium, business, offshore, and institutional banking services; and funds management, superannuation, and share broking products and services, as well as car, health, life, income protection, and travel insurance. In addition, the company offers advisory services for high-net-worth individuals; equities trading and margin lending services; debt capital, transaction banking, working capital, and risk management services; and international and foreign exchange services. Commonwealth Bank of Australia was founded in 1911 and is based in Sydney, Australia.',
 'fullTimeEmployees': 48930,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Matthew  Comyn EMBA',
   'age': 47,
   'title': 'CEO, MD & Executive Director',
   'yearBorn': 1976,
   'fiscalYear': 2023,
   'totalPay': 3754249,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Alan  Docherty',
   'title': 'Group Executive of Financial Services & CFO',
   'fiscalYear': 2023,
   'totalPay': 1688139,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Gavin  Munroe',
   'title': 'Group Executive of Technology & Group Chief Information Officer',
   'fiscalYear': 2023,
   'totalPay': 1726406,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Sian  Lewis',
   'title': 'Group Executive of Human Resources',
   'fiscalYear': 2023,
   'totalPay': 1378852,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nigel  Williams',
   'title': 'Group Chief Risk Officer',
   'fiscalYear': 2023,
   'totalPay': 2032678,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Vittoria Annabel June Shortt BMS, CA',
   'title': 'Chief Executive & MD of ASB Bank Ltd.',
   'fiscalYear': 2023,
   'totalPay': 1564933,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Sinead  Taylor',
   'title': 'Chief Operations Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Rodrigo  Castillo',
   'title': 'Chief Technology Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Melanie  Kirk',
   'title': 'Head of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Karen  O'Flynn",
   'title': 'Group General Counsel, Company Secretary and Group Executive of Legal & Group Secretariat',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 10,
 'boardRisk': 1,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 1,
 'overallRisk': 3,
 'governanceEpochDate': 1709251200,
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 120.07,
 'open': 119.63,
 'dayLow': 117.64,
 'dayHigh': 119.93,
 'regularMarketPreviousClose': 120.07,
 'regularMarketOpen': 119.63,
 'regularMarketDayLow': 117.64,
 'regularMarketDayHigh': 119.93,
 'dividendRate': 4.3,
 'dividendYield': 0.0357,
 'exDividendDate': 1708473600,
 'payoutRatio': 0.78180003,
 'fiveYearAvgDividendYield': 4.29,
 'beta': 0.904,
 'trailingPE': 20.488695,
 'forwardPE': 21.075132,
 'volume': 1941582,
 'regularMarketVolume': 1941582,
 'averageVolume': 2144935,
 'averageVolume10days': 2541656,
 'averageDailyVolume10Day': 2541656,
 'bid': 117.8,
 'ask': 117.83,
 'bidSize': 36400,
 'askSize': 7100,
 'marketCap': 197122048000,
 'fiftyTwoWeekLow': 94.37,
 'fiftyTwoWeekHigh': 121.54,
 'priceToSalesTrailing12Months': 7.5444756,
 'fiftyDayAverage': 116.8308,
 'twoHundredDayAverage': 107.0372,
 'trailingAnnualDividendRate': 4.55,
 'trailingAnnualDividendYield': 0.037894562,
 'currency': 'AUD',
 'enterpriseValue': 380408397824,
 'profitMargins': 0.37037,
 'floatShares': 1667381208,
 'sharesOutstanding': 1673219968,
 'heldPercentInsiders': 0.00427,
 'heldPercentInstitutions': 0.27857,
 'impliedSharesOutstanding': 1673219968,
 'bookValue': 43.529,
 'priceToBook': 2.7064714,
 'lastFiscalYearEnd': 1688083200,
 'nextFiscalYearEnd': 1719705600,
 'mostRecentQuarter': 1703980800,
 'earningsQuarterlyGrowth': -0.08,
 'netIncomeToCommon': 9781999616,
 'trailingEps': 5.75,
 'forwardEps': 5.59,
 'pegRatio': 9.34,
 'lastSplitFactor': '1:1',
 'lastSplitDate': 939168000,
 'enterpriseToRevenue': 14.559,
 '52WeekChange': 0.1892792,
 'SandP52WeekChange': 0.2726959,
 'lastDividendValue': 2.15,
 'lastDividendDate': 1708387200,
 'exchange': 'ASX',
 'quoteType': 'EQUITY',
 'symbol': 'CBA.AX',
 'underlyingSymbol': 'CBA.AX',
 'shortName': 'CWLTH BANK FPO',
 'longName': 'Commonwealth Bank of Australia',
 'firstTradeDateEpochUtc': 686188800,
 'timeZoneFullName': 'Australia/Sydney',
 'timeZoneShortName': 'AEDT',
 'uuid': 'e620b9ab-063f-32b1-9693-269e55eeae5f',
 'messageBoardId': 'finmb_874262',
 'gmtOffSetMilliseconds': 39600000,
 'currentPrice': 117.81,
 'targetHighPrice': 109.7,
 'targetLowPrice': 80.0,
 'targetMeanPrice': 92.2,
 'targetMedianPrice': 92.0,
 'recommendationMean': 4.1,
 'recommendationKey': 'underperform',
 'numberOfAnalystOpinions': 13,
 'totalCash': 132821000192,
 'totalCashPerShare': 79.38,
 'totalDebt': 311869014016,
 'totalRevenue': 26127998976,
 'revenuePerShare': 15.557,
 'returnOnAssets': 0.0078,
 'returnOnEquity': 0.13457,
 'operatingCashflow': -70738001920,
 'earningsGrowth': -0.048,
 'revenueGrowth': -0.022,
 'operatingMargins': 0.5672,
 'financialCurrency': 'AUD',
 'trailingPegRatio': None}

In [3]:
# Time logic block
# Select time input from webpage

time_period = ['d', 'mo', 'y']

In [4]:

# holidays and weekends aren't included in ticker price
shares = ticker_name.get_shares_full(start="2022-01-01", end=None)
history_start_end = ticker_name.history(start='2024-03-21', end='2024-03-28', rounding=True)
history_period = ticker_name.history(period='1mo')
print(history_start_end)

                             Open    High     Low   Close   Volume  Dividends  \
Date
2024-03-21 00:00:00+11:00  117.10  118.05  116.54  118.00  3579903        0.0
2024-03-22 00:00:00+11:00  118.30  118.35  116.56  117.48  3825604        0.0
2024-03-25 00:00:00+11:00  118.25  118.99  117.49  118.79  1974708        0.0
2024-03-26 00:00:00+11:00  118.90  119.49  118.57  118.60  1676353        0.0
2024-03-27 00:00:00+11:00  118.77  120.19  118.51  120.00  2340622        0.0

                           Stock Splits
Date
2024-03-21 00:00:00+11:00           0.0
2024-03-22 00:00:00+11:00           0.0
2024-03-25 00:00:00+11:00           0.0
2024-03-26 00:00:00+11:00           0.0
2024-03-27 00:00:00+11:00           0.0

In [5]:
# Convert to json
ticker_info_df = pd.DataFrame(history_start_end)
ticker_info_df.reset_index(inplace=True)
ticker_info_df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2024-03-21 00:00:00+11:00,117.10,118.05,116.54,118.00,3579903,0.0,0.0
1,2024-03-22 00:00:00+11:00,118.30,118.35,116.56,117.48,3825604,0.0,0.0
2,2024-03-25 00:00:00+11:00,118.25,118.99,117.49,118.79,1974708,0.0,0.0
3,2024-03-26 00:00:00+11:00,118.90,119.49,118.57,118.60,1676353,0.0,0.0
4,2024-03-27 00:00:00+11:00,118.77,120.19,118.51,120.00,2340622,0.0,0.0

In [7]:
ticker_info_json = ticker_info_df.to_json(orient='index')
print(ticker_info_json)

{"0":{"Date":1710939600000,"Open":117.1,"High":118.05,"Low":116.54,"Close":118.0,"Volume":3579903,"Dividends":0.0,"Stock Splits":0.0},"1":{"Date":1711026000000,"Open":118.3,"High":118.35,"Low":116.56,"Close":117.48,"Volume":3825604,"Dividends":0.0,"Stock Splits":0.0},"2":{"Date":1711285200000,"Open":118.25,"High":118.99,"Low":117.49,"Close":118.79,"Volume":1974708,"Dividends":0.0,"Stock Splits":0.0},"3":{"Date":1711371600000,"Open":118.9,"High":119.49,"Low":118.57,"Close":118.6,"Volume":1676353,"Dividends":0.0,"Stock Splits":0.0},"4":{"Date":1711458000000,"Open":118.77,"High":120.19,"Low":118.51,"Close":120.0,"Volume":2340622,"Dividends":0.0,"Stock Splits":0.0}}